export const SET_GESTURE_ACTION = 'SET_GESTURE_ACTION';
export const SET_GAME_SCREEN = 'SET_GAME_SCREEN';
export const SET_HOUSE_GESTURE = 'SET_HOUSE_GESTURE';
export const SET_GESTURE_ANIMATION_END = 'SET_GESTURE_ANIMATION_END';
export const SET_WINNER = 'SET_WINNER';
